version: '3.7'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - ./postgres/postgres.env
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./postgres/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - flightintel-net

  fnsclient:
    image: pr0t0n/fns-client-flightintel:1.4
    container_name: fnsclient
    hostname: fnsclient
    restart: always
    volumes:
      - ./fnsclient/fnsClient.conf:/app/fnsClient.conf:ro
      - ./fnsclient/FIL2_NHASAN_NADMM_COM:/app/FIL2_NHASAN_NADMM_COM:ro
      - ./fnsclient/log4j.properties:/app/log4j.properties:ro
      - ./fnsclient/logs:/app/logs
      - ./fnsclient/tmp:/app/tmp
    depends_on:
      - postgres
    networks:
      - flightintel-net

  tdesclient:
    image: pr0t0n/tdes-client:1.4
    container_name: tdesclient
    hostname: tdesclient
    restart: always
    volumes:
      - ./tdesclient/tdesClient.conf:/app/tdesClient.conf
      - ./tdesclient/log4j.properties:/app/log4j.properties:ro
      - ./tdesclient/logs:/app/logs
    depends_on:
      - postgres
    networks:
      - flightintel-net

networks:
  flightintel-net:
    external: true

